artifacts_root: artifacts #The directory where all data will be stored, preprocessing, transformation, model building etc

#Pulling data from git hub lisk (this can be pulling from API in real projects)
data_ingestion:
  root_dir: artifacts/data_ingestion
  source_URL: https://github.com/Nraghav01/MLOps_github/raw/refs/heads/main/winequality-data.zip #Command to ingest data from git hub repository
  local_data_file: artifacts/data_ingestion/data.zip
  unzip_dir: artifacts/data_ingestion

data_validation:
  root_dir: artifacts/data_validation #Folder for validation data
  unzip_data_dir: artifacts/data_ingestion/winequality-red.csv #Locationof the unziped input file
  STATUS_FILE: artifacts/data_validation/status.txt  #This text logs whether the file is validated or not.


data_transformation:
  root_dir: artifacts/data_transformation
  data_path: artifacts/data_ingestion/winequality-red.csv


model_trainer:
  root_dir: artifacts/model_trainer
  train_data_path: artifacts/data_transformation/train.csv
  test_data_path: artifacts/data_transformation/test.csv
  model_name: model.joblib


model_evaluation:
  root_dir: artifacts/model_evaluation
  test_data_path: artifacts/data_transformation/test.csv
  model_path: artifacts/model_trainer/model.joblib
  metric_file_name: artifacts/model_evaluation/metrics.json
